export const menus: { title: string; children: string[] }[] = [
  {
    title: 'Scene',
    children: ['useNetwork', 'useCounter', 'useWebSocket', 'useVirtualList', 'useDynamicList'],
  },
  {
    title: 'LifeCycle',
    children: ['useMount', 'useUnmount', 'useUnmountedRef'],
  },
  {
    title: 'State',
    children: [
      'useBoolean',
      'useToggle',
      'useLocalStorageState',
      'useSessionStorageState',
      'useCookieState',
      'useDebounce',
      'useThrottle',
      'useSet',
      'useMap',
      'usePrevious',
      'useRafState',
      'useSafeState',
      'useGetState',
    ],
  },
  {
    title: 'Effect',
    children: [
      'useUpdateEffect',
      'useUpdateLayoutEffect',
      'useAsyncEffect',
      'useDebounceFn',
      'useDebounceEffect',
      'useThrottleFn',
      'useThrottleEffect',
      'useTimeout',
      'useRafTimeout',
      'useInterval',
      'useRafInterval',
      'useDeepCompareEffect',
      'useDeepCompareLayoutEffect',
      'useLockFn',
      'useUpdate',
    ],
  },
  {
    title: 'Dom',
    children: [
      'useEventListener',
      'useEventTarget',
      'useExternal',
      'useTitle',
      'useFavicon',
      'useSize',
      'useHover',
      'useMouse',
      'useScroll',
      'useFullscreen',
      'useInViewport',
      'useFocusWithin',
      'useKeyPress',
      'useLongPress',
    ],
  },
  {
    title: 'Advanced',
    children: [
      'useLatest',
      'useMemoizedFn',
      'useEventEmitter',
      'useCreation',
      'useReactive',
      'useIsomorphicLayoutEffect',
      'useControllableValue',
    ],
  },
  {
    title: 'Dev',
    children: ['useTrackedEffect', 'useWhyDidYouUpdate'],
  },
];
