export const menus = [
  {
    title: 'LifeCycle',
    children: ['useMount', 'useUnmount', 'useUnmountedRef'],
  },
  {
    title: 'State',
    children: [
      'useBoolean',
      'useToggle',
      'useLocalStorageState',
      'useSessionStorageState',
      'useCookieState',
      'useDebounce',
      'useThrottle',
      'useSet',
      'useMap',
      'usePrevious',
      'useRafState',
      'useSafeState',
      'useGetState',
    ],
  },
  {
    title: 'Effect',
    children: [
      'useUpdateEffect',
      'useUpdateLayoutEffect',
      'useAsyncEffect',
      'useDebounceFn',
      'useDebounceEffect',
      'useThrottleFn',
      'useThrottleEffect',
      'useTimeout',
      'useRafTimeout',
      'useInterval',
      'useRafInterval',
      'useLockFn',
      'useUpdate',
    ],
  },
  {
    title: 'Dom',
    children: [
      'useEventListener',
      'useEventTarget',
      'useExternal',
      'useTitle',
      'useFavicon',
      'useSize',
      'useMouse',
      'useFocusWithin',
    ],
  },
  {
    title: 'Advanced',
    children: ['useLatest', 'useMemoizedFn', 'useEventEmitter', 'useCreation', 'useReactive'],
  },
];
